server:
  port: 5000

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/fassets
    username: root
    password: midnighttrain
    driverClassName: org.mariadb.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddlAuto: update
    show-sql: true